### ISSUE TITLE
SM3 compatible

### ISSUE THREAD

**Issue by malinink** [juriansluiman/SlmQueueDoctrine#100]
Is there any plans to be compatible with SM3?

I could provide necessary PR.

**Comment by basz** [comment]
I don't have the complete picture of what needs do be done for sm3 compatibility nor if if can be done without a BC break. But I'm sure any PR will be considered, so please go ahead if you have a need for it.

**Comment by malinink** [comment]
@basz 
Hi, I looked again into my PR in SQD module, and figure out that not all test worked fine. Soon I will provide new PR.
Don't make release on SQD before it. Thanks!

**Comment by basz** [comment]
I think all is fine at the moment. Please have a look at this PR (test if you can with and without doctrine from your own branches) which includes your sm3 work and additionally add support for eventmanager 2.7||3.0

**Comment by malinink** [comment]
I'll  try to test that in my project tomorrow. I look both PR, yes EM is that I told about.

**Comment by basz** [comment]
The event manager works different in many ways then we are using it in the worker. I now have got it working but it isn't pretty.

Basically we used to use the event as an object that is passed around contains results of job, marks if propagation should stop and is the loop should exit. A lot of state is in there.
The new em discourages this by cloning passed events and basically is a one way thing. Results may be returned in listeners but those should not really be events. I'm cheating now and am still doing that. The basicly a hacky.
I would like to think on this for a bit... I'll push the sort of working version tonight or tomorrow morning for you to play with...

**Comment by basz** [comment]
@malinink have a look at how the events work now (just pushed the repo's) with : https://github.com/basz/sim-queue-test-application

Not happy with how different the events are handled currently but it seems to work...

Ideally I think i would like to see
```
ProcessJobEvent extends WorkerEvent
IdleEvent extends WorkerEvent
etc.
```

Along with specialised result classes we can use returned collections.

```
ProcessJobResult
ProcessQueueResult
QueueStateResult
etc...
```

Do you have suggestions for this?

**Comment by malinink** [comment]
@basz 
I try to integrate new branches and failed on it. It seems like events not working at all.

I'm sorry that I have not research more precisely, have a lot of work now. I could try to look in a next week.

About Events, I did not look at them yet, but I could, after that I provide advices if have one.
