### ISSUE TITLE
Clear any outstanding jobs given the job name

### ISSUE THREAD

**Issue by kelsey9649** [juriansluiman/SlmQueueDoctrine#101]
I've been using some jobs that are self-enqueueing to run a job every so many minutes. I use a console command to seed the job into the queue and then it runs. As business requirements change, the delay between the job runs change. I made a console command parameter to pass in, updating the delay, but it results in two sets of the command in the queue running alongside each other. I was thinking it might make a nice feature to have a command to clear out any pending jobs given the job name. It would help out this specific case. (I'm not opposed to creating the PR, let me know if you think this fits appropriately in the project)

**Comment by basz** [comment]
Sorry ‘bout the delay.

Can’t the self enqueuing job have access to the delay property that changes over time and reinsert with the new delay once it has run?

Or, if the delay is too long. I would create an ‘heartbeat’ job that runs regularly (10s) which either reinserts itself or the actual job based on  your delay threshold for the actual job. Once that has run it will queue another heartbeat or real job. Etc...

Deleting a pending job from a queue should’t be possible. Fire and forget...  not even possible for some adapters. 
that said, you could always write a quick sql to do anything with the queue table. Perhaps by extending the queue with your own implementation.
