### ISSUE TITLE
Configure a Worker class for Doctrine Worker Controller

### ISSUE THREAD

**Issue by gennadiylitvinyuk** [juriansluiman/SlmQueueDoctrine#102]
Is it possible to configure a WorkerClass (or a Worker Class Factory) to use with Doctrine Worker Controller, if the standard Worker should be adapted?

Or it should be done with new Controller (+Factory) and Worker (+Factory)?

**Comment by basz** [comment]
Not sure what you are trying to accomplish. I believe the DoctrineWorkerController is specific to the provided Worker with this package. Different adapters use there own implementation.

Please elaborate on what you are trying to do, perhaps you should create a new adapter repo...

**Comment by gennadiylitvinyuk** [comment]
My goal is to make a new Worker, which allows explicit Job processing, similar to one in ZF1/SQS. The removal of the Job from the Queue happens only if Job has explicitly confirmed, that it was done. In the other case it will be recovered/buried depending on Worker logic.

The DoctrineController does his job in this case well, and I do not see any reason to change it. The only thing I want to change is the Worker / Job communication, because communicating though Exceptions does not look proper to me, but it seems that DoctrineWorker is strong coupled with Doctrine Controller and can't be easily replaced.

**Comment by basz** [comment]
I think you could write an alternative [Controller](https://github.com/juriansluiman/SlmQueueDoctrine/blob/master/src/Controller/DoctrineWorkerController.php) and [ControllerFactory](https://github.com/juriansluiman/SlmQueueDoctrine/blob/master/src/Factory/DoctrineWorkerControllerFactory.php) or [Worker](https://github.com/juriansluiman/SlmQueueDoctrine/blob/master/src/Worker/DoctrineWorker.php) and [WorkerFactory](https://github.com/juriansluiman/SlmQueueDoctrine/blob/master/src/Factory/DoctrineWorkerControllerFactory.php) and activate those factories [here](https://github.com/juriansluiman/SlmQueueDoctrine/blob/master/config/module.config.php#L18) and [here](https://github.com/juriansluiman/SlmQueueDoctrine/blob/master/config/module.config.php#L13).

Indeed the current behaviour for Jobs is that you don't have explicitly mark a job as successful - no errors and finished means it is marked as complete and ready for garbage collection. A job shouldn't have to care about itself. If you are looking for a way do repeat a job until some criteria has been met, I would suggest you look into the capability of a Job to access the queue and reinsert itself or other Jobs. To do this Implement the [QueueAwareInterface](https://github.com/juriansluiman/SlmQueue/blob/master/src/Queue/QueueAwareInterface.php) and then you can do something like this in the execute method of the Job;

```
    public function execute()
    {
        // work

        if (true == $notfinsihed) {
            // release() is Doctrine Adapter specific and reinsert the job
            // delay is optional will schedule 5s in the future
            $this->getQueue()->release($this, ['delay' => 5]); 
        }

       // or create a new instance
        $content = $this->getContent();
        if ($content['times_executed'] < 10) {
            $job = new static();
            $job->setContent($content['times_executed']++);
            $this->getQueue()->push($job);
        }
    }
```
