### ISSUE TITLE
Upgrade SlmQueue dependency to 0.7

### ISSUE THREAD

**Issue by kokx** [juriansluiman/SlmQueueDoctrine#115]
Currently, it is impossible to use SlmQueue 0.7 with SlmQueueDoctrine, since in `composer.json` it is still fixed to version `^0.6`.

However, they are compatible. Hence, it would be nice to upgrade the version constraint to 0.7.

**Comment by basz** [comment]
thanks for bringing this to my attention. 0.7 has been released
