### ISSUE TITLE
Jobs can not be given a priority

### ISSUE THREAD

**Issue by roelvanduijnhoven** [juriansluiman/SlmQueueDoctrine#122]
I want to schedule some work with a lower priority. However this is not possible with this adapter. And thus we resort to running multiple queue's: so that large chunks can run in a separate thread and will not block more important work.

The Beanstalk plugin *does* support this (https://github.com/juriansluiman/SlmQueueBeanstalkd#operations-on-queues). 

Would a PR that introcues this be merged in this repo? Or is there a reason this is not implemented at this time?

**Comment by basz** [comment]
yes it would

**Comment by roelvanduijnhoven** [comment]
Allright; I'll take a stab at it sometime!

**Comment by basz** [comment]
tagged v2.0 thanks great addition!

**Comment by roelvanduijnhoven** [comment]
Thanks for iterating so fast with me! I'll be rolling out a new release of jouwweb.nl later today using this :).

**Comment by basz** [comment]
ah, nice :-)



€0*  per maand €8
