### ISSUE TITLE
Zend Expressive

### ISSUE THREAD

**Issue by imonteiro** [juriansluiman/SlmQueueDoctrine#145]
Hi,

Currently I'm migrating an Zend MVC application to Zend Expressive, which use this module.

SlmQueue is already Expressive "ready".
Anyone has used SlmQueueDoctrine with Zend Expressive? Or you are using another adapter (Sqs)?

Thanks.

IM

**Comment by basz** [comment]
Yes it works in expressive

**Comment by imonteiro** [comment]
@basz Thanks for you quick answer. I will give a try.

As this module require doctrine-module-orm I'm wondering if make sense find a way to avoid zend-mvc requirement.

**Comment by basz** [comment]
If I remember correctly I needed to massage the doctrine-orm-module config a bit. Can look it up later... ping me when I forget

**Comment by imonteiro** [comment]
@basz ping (thanks)

**Comment by basz** [comment]
Hi, I dropped one file into `config/autoload/` file I now see.  

https://gist.github.com/basz/0871efbaf38cd831c972c25635b7d056

**Comment by imonteiro** [comment]
@basz I got it.

I have prepared a branch in my forks of SlmQueue and SlmQueueDoctrine to load the configuration with ConfigProvider. If you agree I can make a pull request to each repo.

Regarding the composer file we should set "doctrine/doctrine-orm-module" optional as we can use 
https://github.com/DASPRiD/container-interop-doctrine instead. What do you think?

**Comment by basz** [comment]
> I have prepared a branch in my forks of SlmQueue and SlmQueueDoctrine to load the configuration with ConfigProvider. If you agree I can make a pull request to each repo.

Yes, please...

> Regarding the composer file we should set "doctrine/doctrine-orm-module" optional as we can use
https://github.com/DASPRiD/container-interop-doctrine instead.

I wasn't aware of that package. If you think it’s useful please go ahead. What do you think @roelvanduijnhoven

**Comment by roelvanduijnhoven** [comment]
Having `doctrine/doctrine-orm-module` as a dependency will also pull in the MVC part of ZF. So I guess by changing to `DASPRiD/container-interop-doctrine` we lose that dependency. That's fine. 

However, won't this give any problems if you are using SlmQueueDoctrine together *with* ZF? Won't this lead to duplicated Doctrine connections instances? No experience with DASPRiD/container-interop-doctrine, so not sure on that part.

**Comment by imonteiro** [comment]
I'm using _DASPRiD/container-interop-doctrine_ with expressive and so far so good, basically is just a  PSR container with a bunch of factories.

However, I didn't tested with SlmQueueDoctrine.

**Comment by roelvanduijnhoven** [comment]
Yeah so we should verify or test whether Doctrine works if both `dasprid/container-interop-doctrine` and `doctrine/doctrine-orm-module` are used. IMO it should not lead to multiple instances of Doctrine objects. Maybe this is trivially true, but I am not sure.

**Comment by imonteiro** [comment]
I have created https://github.com/JouwWeb/SlmQueue/pull/220 and https://github.com/juriansluiman/SlmQueueDoctrine/pull/146 pull requests to include the ConfigProvider.

https://github.com/juriansluiman/SlmQueueDoctrine/pull/147 pull request it's related with Doctrine PSR container, but I not yet tested using dasprid/container-interop-doctrine and doctrine/doctrine-orm-module at the same time and there is still some work to do with tests.
