### ISSUE TITLE
Question: The worker executes tasks simultaneously?

### ISSUE THREAD

**Issue by uchihacash** [juriansluiman/SlmQueueDoctrine#93]
Great project

I am developing an online store in which trade game codes

When I receive multiple requests to the server to buy, these are executed simultaneously in PHP,

I want to avoid collisions and ship one by one.

With SmlQueue I can send one by one and not several at once?

**Comment by bakura10** [comment]
Hi,

SlmQueue does not guarantee that. You must handle such issues at another level. For instance, if a game code could only be trade once by a user, you should ensure atomicity using unique constraints on database, for instance. Therefore, the first time it will be executed, the request will succeed, but second time database will reject.

On SlmQueue, nothing prevent you to insert a job multiple times and, hence, executing the same job multiple times.
