### ISSUE TITLE
SlmQueue Doctrine using shared event manager does not retrieve job's result

### ISSUE THREAD

**Issue by ceadreak** [juriansluiman/SlmQueueDoctrine#94]
Hi team, 

Hope you’re fine.

I’m writing an application using ZF2, PostgreSQL, Doctrine.

For a newsletter sending process, I use SlmQueue.
I have 2 jobs : 
- members synchronization with mailservice
- newsletter sending process

My problem is basic : 
I want to stop the queue if the first job is not completely terminated !

To achieve that, I’m using the shared event manager such as the doc :

      Module.php 
  
      public function onBootstrap(MvcEvent $e)
        {    
            $sharedEventManager->attach('SlmQueue\Worker\WorkerInterface', WorkerEvent::EVENT_PROCESS_JOB, function (WorkerEvent $e)
            {
                // a problem has been detected on the running job
                $result = $e->getResult();
                if (WorkerEvent::JOB_STATUS_FAILURE === $result) {
                    $job = $e->getJob();
                    die(sprintf(
                        'Job #%s (%s) failed executing', $job->getId, get_class($job)
                    ));
                }
             }, 1000);
        }

The jobs successfully failed but the program never come in the if() statement (getResult() = 0).
I verified the returned status of the processJob() method in DoctrineWorker.php file and it’s 3 (= JOB_STATUS_FAILURE)

Is this a bug ? Or maybe I’m totally wrong with my program ?

Thanks for your answer.

Regards,
Cedric

**Comment by basz** [comment]
I don't think it is a good idea to exit the worker if a particular job won't successfully process, but if you must I think this might help: Provide a negative priority on attach WorkerEvent::EVENT_PROCESS_JOB as that will ensure this handler is run *after* the job has been processed.

It would be more elegant to have your 'members synchronization with mailservice' Job add the 'newsletter sending process' when it can successfully do its thing.
```
class MyJob implements QueueAware {
  function execute() {
    do work...
 
    when success
      add OtherJob to Queue
      // $this->getQueue(new OtherJob()
  }
}
```
As a hack I put this together https://github.com/bushbaby/BsbPostponableJobStrategy which might help you define dependencies between Jobs.

**Comment by ceadreak** [comment]
Thanks for your answer.

A negative priority doesn't do the trick, I got an error type 

    Undefined property: ...\SynchronizeMembersJob::$getId in .../Admin/Module.php

So, I'll try the second solution with job dependency

**Comment by basz** [comment]
The code is working, that error is because you use `$job->getId` instead of `$job->getId()`

**Comment by ceadreak** [comment]
Damn ... Thanks.

Copy / Paste from doc ;)
